import React, { createContext, useContext, useState, useEffect } from 'react';
import { defaultProducts } from '../data/products';

const AppContext = createContext();
export const useApp = () => useContext(AppContext);

// Admin credentials (sirf aap jaante ho)
const ADMIN_EMAIL = 'admin@veloracart.com';
const ADMIN_PASS = 'VeloraAdmin@2025';

export const AppProvider = ({ children }) => {
  // Auth
    const [user, setUser] = useState(null);
      const [isAdmin, setIsAdmin] = useState(false);
        
          // Products
            const [products, setProducts] = useState([]);
              
                // Cart & Wishlist
                  const [cartItems, setCartItems] = useState([]);
                    const [wishlist, setWishlist] = useState([]);
                      const [orders, setOrders] = useState([]);
                        
                          // UI
                            const [isCartOpen, setIsCartOpen] = useState(false);
                              const [isWishlistOpen, setIsWishlistOpen] = useState(false);
                                const [isAdminPanelOpen, setIsAdminPanelOpen] = useState(false);
                                  const [theme, setTheme] = useState('dark');
                                    const [notifications, setNotifications] = useState([]);
                                      const [searchQuery, setSearchQuery] = useState('');
                                        const [loading, setLoading] = useState(true);

                                          // Load saved data
                                            useEffect(() => {
                                                const savedUser = localStorage.getItem('velora_user');
                                                    const savedProducts = localStorage.getItem('velora_products');
                                                        const savedCart = localStorage.getItem('velora_cart');
                                                            const savedWishlist = localStorage.getItem('velora_wishlist');
                                                                const savedOrders = localStorage.getItem('velora_orders');
                                                                    const savedTheme = localStorage.getItem('velora_theme');

                                                                        if (savedUser) {
                                                                              const u = JSON.parse(savedUser);
                                                                                    setUser(u);
                                                                                          setIsAdmin(u.role === 'admin');
                                                                                              }
                                                                                                  setProducts(savedProducts ? JSON.parse(savedProducts) : defaultProducts);
                                                                                                      if (savedCart) setCartItems(JSON.parse(savedCart));
                                                                                                          if (savedWishlist) setWishlist(JSON.parse(savedWishlist));
                                                                                                              if (savedOrders) setOrders(JSON.parse(savedOrders));
                                                                                                                  if (savedTheme) setTheme(savedTheme);

                                                                                                                      setTimeout(() => setLoading(false), 2500);
                                                                                                                        }, []);

                                                                                                                          // Auto save
                                                                                                                            useEffect(() => { localStorage.setItem('velora_products', JSON.stringify(products)); }, [products]);
                                                                                                                              useEffect(() => { localStorage.setItem('velora_cart', JSON.stringify(cartItems)); }, [cartItems]);
                                                                                                                                useEffect(() => { localStorage.setItem('velora_wishlist', JSON.stringify(wishlist)); }, [wishlist]);
                                                                                                                                  useEffect(() => { localStorage.setItem('velora_orders', JSON.stringify(orders)); }, [orders]);
                                                                                                                                    useEffect(() => { localStorage.setItem('velora_theme', theme); document.body.className = theme; }, [theme]);

                                                                                                                                      // Auth functions
                                                                                                                                        const login = (email, password) => {
                                                                                                                                            if (email === ADMIN_EMAIL && password === ADMIN_PASS) {
                                                                                                                                                  const admin = { name: 'Admin', email, role: 'admin', avatar: '👑' };
                                                                                                                                                        setUser(admin);
                                                                                                                                                              setIsAdmin(true);
                                                                                                                                                                    localStorage.setItem('velora_user', JSON.stringify(admin));
                                                                                                                                                                          addNotification('👑 Welcome back, Admin!', 'success');
                                                                                                                                                                                return { success: true, admin: true };
                                                                                                                                                                                    }
                                                                                                                                                                                        if (email && password && password.length >= 6) {
                                                                                                                                                                                              const u = { name: email.split('@')[0], email, role: 'user', avatar: email.charAt(0).toUpperCase() };
                                                                                                                                                                                                    setUser(u);
                                                                                                                                                                                                          setIsAdmin(false);
                                                                                                                                                                                                                localStorage.setItem('velora_user', JSON.stringify(u));
                                                                                                                                                                                                                      addNotification(`✨ Welcome, ${u.name}!`, 'success');
                                                                                                                                                                                                                            return { success: true, admin: false };
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                    return { success: false, error: 'Invalid credentials' };
                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                        const logout = () => {
                                                                                                                                                                                                                                            setUser(null);
                                                                                                                                                                                                                                                setIsAdmin(false);
                                                                                                                                                                                                                                                    localStorage.removeItem('velora_user');
                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                        // Cart
                                                                                                                                                                                                                                                          const addToCart = (product, qty = 1) => {
                                                                                                                                                                                                                                                              setCartItems(prev => {
                                                                                                                                                                                                                                                                    const existing = prev.find(i => i.id === product.id);
                                                                                                                                                                                                                                                                          if (existing) return prev.map(i => i.id === product.id ? { ...i, quantity: i.quantity + qty } : i);
                                                                                                                                                                                                                                                                                return [...prev, { ...product, quantity: qty }];
                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                        addNotification(`🛒 ${product.name} added to cart`, 'success');
                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                            const removeFromCart = (id) => setCartItems(prev => prev.filter(i => i.id !== id));
                                                                                                                                                                                                                                                                                              const updateQuantity = (id, delta) => {
                                                                                                                                                                                                                                                                                                  setCartItems(prev => prev.map(i => i.id === id ? { ...i, quantity: Math.max(1, i.quantity + delta) } : i));
                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                      const clearCart = () => setCartItems([]);

                                                                                                                                                                                                                                                                                                        // Wishlist
                                                                                                                                                                                                                                                                                                          const toggleWishlist = (product) => {
                                                                                                                                                                                                                                                                                                              setWishlist(prev => {
                                                                                                                                                                                                                                                                                                                    const exists = prev.find(i => i.id === product.id);
                                                                                                                                                                                                                                                                                                                          if (exists) {
                                                                                                                                                                                                                                                                                                                                  addNotification('💔 Removed from wishlist', 'info');
                                                                                                                                                                                                                                                                                                                                          return prev.filter(i => i.id !== product.id);
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                      addNotification('❤️ Added to wishlist', 'success');
                                                                                                                                                                                                                                                                                                                                                            return [...prev, product];
                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                    const isInWishlist = (id) => wishlist.some(i => i.id === id);

                                                                                                                                                                                                                                                                                                                                                                      // Orders
                                                                                                                                                                                                                                                                                                                                                                        const placeOrder = (details) => {
                                                                                                                                                                                                                                                                                                                                                                            const order = {
                                                                                                                                                                                                                                                                                                                                                                                  id: 'ORD-' + Date.now(),
                                                                                                                                                                                                                                                                                                                                                                                        items: cartItems,
                                                                                                                                                                                                                                                                                                                                                                                              total: cartTotal,
                                                                                                                                                                                                                                                                                                                                                                                                    date: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                          status: 'Processing',
                                                                                                                                                                                                                                                                                                                                                                                                                ...details
                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                        setOrders(prev => [order, ...prev]);
                                                                                                                                                                                                                                                                                                                                                                                                                            clearCart();
                                                                                                                                                                                                                                                                                                                                                                                                                                addNotification('🎉 Order placed successfully!', 'success');
                                                                                                                                                                                                                                                                                                                                                                                                                                    return order;
                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                        // Admin: Product CRUD
                                                                                                                                                                                                                                                                                                                                                                                                                                          const addProduct = (product) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                              const newProduct = { ...product, id: Date.now(), reviews: 0 };
                                                                                                                                                                                                                                                                                                                                                                                                                                                  setProducts(prev => [newProduct, ...prev]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      addNotification('✅ Product added', 'success');
                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                          const updateProduct = (id, updates) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                              setProducts(prev => prev.map(p => p.id === id ? { ...p, ...updates } : p));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  addNotification('✅ Product updated', 'success');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const deleteProduct = (id) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setProducts(prev => prev.filter(p => p.id !== id));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              addNotification('🗑️ Product deleted', 'info');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Notifications
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const addNotification = (message, type = 'info') => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const id = Date.now() + Math.random();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setNotifications(prev => [...prev, { id, message, type }]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setTimeout(() => setNotifications(prev => prev.filter(n => n.id !== id)), 3000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Computed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const cartTotal = cartItems.reduce((s, i) => s + i.price * i.quantity, 0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const cartCount = cartItems.reduce((s, i) => s + i.quantity, 0);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <AppContext.Provider value={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Auth
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          user, isAdmin, login, logout,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Products
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      products, addProduct, updateProduct, deleteProduct,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Cart
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cartItems, addToCart, removeFromCart, updateQuantity, clearCart,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cartTotal, cartCount, isCartOpen, setIsCartOpen,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Wishlist
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    wishlist, toggleWishlist, isInWishlist, isWishlistOpen, setIsWishlistOpen,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Orders
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                orders, placeOrder,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Admin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            isAdminPanelOpen, setIsAdminPanelOpen,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // UI
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        theme, setTheme, notifications, addNotification,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              searchQuery, setSearchQuery, loading
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {children}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </AppContext.Provider>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }