import React from 'react';
import { useCart } from '../context/CartContext';

const Cart = () => {
  const { cartItems, removeFromCart, updateQuantity, cartTotal, cartCount, isCartOpen, setIsCartOpen } = useCart();

    return (
        <>
              <div className={`cart-overlay ${isCartOpen ? 'active' : ''}`} onClick={() => setIsCartOpen(false)} />
                    <div className={`cart-sidebar ${isCartOpen ? 'active' : ''}`}>
                            <div className="cart-header">
                                      <div className="cart-header-title">
                                                  🛍️ Your Cart <span className="cart-count">{cartCount}</span>
                                                            </div>
                                                                      <button className="cart-close" onClick={() => setIsCartOpen(false)}>✕</button>
                                                                              </div>

                                                                                      <div className="cart-items">
                                                                                                {cartItems.length === 0 ? (
                                                                                                            <div className="cart-empty">
                                                                                                                          <div className="cart-empty-icon">🛒</div>
                                                                                                                                        <div className="cart-empty-text">Your cart is empty</div>
                                                                                                                                                      <div className="cart-empty-sub">Add some products to get started!</div>
                                                                                                                                                                  </div>
                                                                                                                                                                            ) : (
                                                                                                                                                                                        cartItems.map(item => (
                                                                                                                                                                                                      <div key={item.id} className="cart-item">
                                                                                                                                                                                                                      <div className="cart-item-image">{item.emoji}</div>
                                                                                                                                                                                                                                      <div className="cart-item-details">
                                                                                                                                                                                                                                                        <div className="cart-item-name">{item.name}</div>
                                                                                                                                                                                                                                                                          <div className="cart-item-price">${item.price}</div>
                                                                                                                                                                                                                                                                                            <div className="cart-item-controls">
                                                                                                                                                                                                                                                                                                                <button className="cart-qty-btn" onClick={() => updateQuantity(item.id, -1)}>−</button>
                                                                                                                                                                                                                                                                                                                                    <span className="cart-item-qty">{item.quantity}</span>
                                                                                                                                                                                                                                                                                                                                                        <button className="cart-qty-btn" onClick={() => updateQuantity(item.id, 1)}>+</button>
                                                                                                                                                                                                                                                                                                                                                                            <button className="cart-item-remove" onClick={() => removeFromCart(item.id)}>🗑️</button>
                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {cartItems.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="cart-footer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="cart-summary-row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span>Subtotal</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span>${cartTotal.toFixed(2)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="cart-summary-row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span>Shipping</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span style={{ color: '#10b981' }}>Free</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="cart-total-row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="cart-total-label">Total</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="cart-total-amount">${cartTotal.toFixed(2)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button className="cart-checkout-btn">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  💳 Checkout Now
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default Cart;