import React, { useEffect, useRef } from 'react';
import ParticleBackground from './components/ParticleBackground';

const ParticleBackground = () => {
  const canvasRef = useRef(null);

    useEffect(() => {
        const canvas = canvasRef.current;
            if (!canvas) return;
                const ctx = canvas.getContext('2d');
                    let animationFrameId;

                        let width = (canvas.width = window.innerWidth);
                            let height = (canvas.height = window.innerHeight);

                                const handleResize = () => {
                                      width = canvas.width = window.innerWidth;
                                            height = canvas.height = window.innerHeight;
                                                };
                                                    window.addEventListener('resize', handleResize);

                                                        // Particle Configuration
                                                            const particleCount = window.innerWidth < 768 ? 35 : 70;
                                                                const particles = [];
                                                                    const colors = ['#a855f7', '#6366f1', '#ec4899', '#3b82f6'];

                                                                        for (let i = 0; i < particleCount; i++) {
                                                                              particles.push({
                                                                                      x: Math.random() * width,
                                                                                              y: Math.random() * height,
                                                                                                      radius: Math.random() * 2.5 + 1,
                                                                                                              color: colors[Math.floor(Math.random() * colors.length)],
                                                                                                                      vx: (Math.random() - 0.5) * 0.6,
                                                                                                                              vy: (Math.random() - 0.5) * 0.6,
                                                                                                                                      alpha: Math.random() * 0.5 + 0.2,
                                                                                                                                            });
                                                                                                                                                }

                                                                                                                                                    // Animation Loop
                                                                                                                                                        const render = () => {
                                                                                                                                                              ctx.clearRect(0, 0, width, height);

                                                                                                                                                                    // Draw particle connections (constellation effect)
                                                                                                                                                                          for (let i = 0; i < particles.length; i++) {
                                                                                                                                                                                  for (let j = i + 1; j < particles.length; j++) {
                                                                                                                                                                                            const dx = particles[i].x - particles[j].x;
                                                                                                                                                                                                      const dy = particles[i].y - particles[j].y;
                                                                                                                                                                                                                const dist = Math.sqrt(dx * dx + dy * dy);

                                                                                                                                                                                                                          if (dist < 120) {
                                                                                                                                                                                                                                      ctx.beginPath();
                                                                                                                                                                                                                                                  ctx.strokeStyle = `rgba(168, 85, 247, ${0.15 * (1 - dist / 120)})`;
                                                                                                                                                                                                                                                              ctx.lineWidth = 0.8;
                                                                                                                                                                                                                                                                          ctx.moveTo(particles[i].x, particles[i].y);
                                                                                                                                                                                                                                                                                      ctx.lineTo(particles[j].x, particles[j].y);
                                                                                                                                                                                                                                                                                                  ctx.stroke();
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                // Draw glowing particles
                                                                                                                                                                                                                                                                                                                                      particles.forEach(p => {
                                                                                                                                                                                                                                                                                                                                              p.x += p.vx;
                                                                                                                                                                                                                                                                                                                                                      p.y += p.vy;

                                                                                                                                                                                                                                                                                                                                                              if (p.x < 0) p.x = width;
                                                                                                                                                                                                                                                                                                                                                                      if (p.x > width) p.x = 0;
                                                                                                                                                                                                                                                                                                                                                                              if (p.y < 0) p.y = height;
                                                                                                                                                                                                                                                                                                                                                                                      if (p.y > height) p.y = 0;

                                                                                                                                                                                                                                                                                                                                                                                              ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                                                      ctx.arc(p.x, p.y, p.radius, 0, Math.PI * 2);
                                                                                                                                                                                                                                                                                                                                                                                                              ctx.fillStyle = p.color;
                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.globalAlpha = p.alpha;
                                                                                                                                                                                                                                                                                                                                                                                                                              ctx.shadowBlur = 12;
                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.shadowColor = p.color;
                                                                                                                                                                                                                                                                                                                                                                                                                                              ctx.fill();
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.globalAlpha = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                              ctx.shadowBlur = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          animationFrameId = requestAnimationFrame(render);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  render();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            window.removeEventListener('resize', handleResize);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cancelAnimationFrame(animationFrameId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <canvas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ref={canvasRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  position: 'fixed',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          top: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  left: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          width: '100%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  height: '100%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          pointerEvents: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  zIndex: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default ParticleBackground