import React, { useState, useEffect, useRef } from 'react';

const Deals = () => {
  const ref = useRef();
    const [time, setTime] = useState({ hours: 23, minutes: 45, seconds: 30 });

      useEffect(() => {
          const timer = setInterval(() => {
                setTime(prev => {
                        let { hours, minutes, seconds } = prev;
                                seconds--;
                                        if (seconds < 0) { seconds = 59; minutes--; }
                                                if (minutes < 0) { minutes = 59; hours--; }
                                                        if (hours < 0) { hours = 23; minutes = 59; seconds = 59; }
                                                                return { hours, minutes, seconds };
                                                                      });
                                                                          }, 1000);
                                                                              return () => clearInterval(timer);
                                                                                }, []);

                                                                                  useEffect(() => {
                                                                                      const observer = new IntersectionObserver(
                                                                                            entries => entries.forEach(e => e.isIntersecting && e.target.classList.add('visible')),
                                                                                                  { threshold: 0.1 }
                                                                                                      );
                                                                                                          ref.current?.querySelectorAll('.fade-up').forEach(el => observer.observe(el));
                                                                                                              return () => ref.current?.querySelectorAll('.fade-up').forEach(el => observer.unobserve(el));
                                                                                                                }, []);

                                                                                                                  return (
                                                                                                                      <section className="deals" id="deals" ref={ref}>
                                                                                                                            <div className="section-container">
                                                                                                                                    <div className="deals-banner fade-up">
                                                                                                                                              <div className="deals-content">
                                                                                                                                                          <div className="deals-tag">⚡ Flash Sale</div>
                                                                                                                                                                      <h2 className="deals-title">
                                                                                                                                                                                    Mega Deal<br />
                                                                                                                                                                                                  <span style={{ background: 'var(--gradient1)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
                                                                                                                                                                                                                  Up to 60% Off
                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                            </h2>
                                                                                                                                                                                                                                                        <p className="deals-desc">
                                                                                                                                                                                                                                                                      Don't miss out on our biggest sale of the year. Limited time offers on premium products.
                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                              <div className="deals-timer">
                                                                                                                                                                                                                                                                                                            <div className="deals-timer-item">
                                                                                                                                                                                                                                                                                                                            <div className="deals-timer-num">{String(time.hours).padStart(2, '0')}</div>
                                                                                                                                                                                                                                                                                                                                            <div className="deals-timer-label">Hours</div>
                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                        <div className="deals-timer-item">
                                                                                                                                                                                                                                                                                                                                                                                        <div className="deals-timer-num">{String(time.minutes).padStart(2, '0')}</div>
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="deals-timer-label">Mins</div>
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="deals-timer-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="deals-timer-num">{String(time.seconds).padStart(2, '0')}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="deals-timer-label">Secs</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button className="hero-btn-primary" onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('products')?.scrollIntoView({ behavior: 'smooth' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  🛍️ Shop the Sale
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="deals-visual">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="deals-product-img">👟</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="deals-discount">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="deals-discount-text">60%</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="deals-discount-label">OFF</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default Deals;