import React from 'react';

const Footer = () => {
  return (
      <footer className="footer">
            <div className="section-container">
                    <div className="footer-grid">
                              <div>
                                          <div className="nav-logo" style={{ marginBottom: 5 }}>
                                                        <div className="nav-logo-box">🛒</div>
                                                                      <span className="nav-logo-text">VeloraCart</span>
                                                                                  </div>
                                                                                              <p className="footer-brand-desc">
                                                                                                            Your premium shopping destination. Discover curated collections 
                                                                                                                          of the finest products from around the world.
                                                                                                                                      </p>
                                                                                                                                                  <div className="footer-social">
                                                                                                                                                                {['📘', '🐦', '📸', '🎵'].map((icon, i) => (
                                                                                                                                                                                <button key={i} className="footer-social-btn">{icon}</button>
                                                                                                                                                                                              ))}
                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                          <h4 className="footer-col-title">Quick Links</h4>
                                                                                                                                                                                                                                                      <ul className="footer-links">
                                                                                                                                                                                                                                                                    {['Home', 'Products', 'Categories', 'Deals', 'About Us'].map(link => (
                                                                                                                                                                                                                                                                                    <li key={link} className="footer-link">→ {link}</li>
                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                              </ul>
                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                              <h4 className="footer-col-title">Support</h4>
                                                                                                                                                                                                                                                                                                                                                          <ul className="footer-links">
                                                                                                                                                                                                                                                                                                                                                                        {['Help Center', 'Shipping Info', 'Returns', 'Track Order', 'Contact Us'].map(link => (
                                                                                                                                                                                                                                                                                                                                                                                        <li key={link} className="footer-link">→ {link}</li>
                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                  </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h4 className="footer-col-title">Contact</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ul className="footer-links">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <li className="footer-link">📍 123 Velora Street, NY</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <li className="footer-link">📞 +1 (234) 567-890</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li className="footer-link">📧 hello@veloracart.com</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <li className="footer-link">🕐 Mon - Fri, 9AM - 6PM</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="footer-bottom">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="footer-copyright">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  © 2025 VeloraCart. All rights reserved. Made with 💜
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="footer-payments">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {['VISA', 'MC', 'AMEX', 'PP'].map(p => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span key={p} className="footer-payment">{p}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default Footer;