import React, { useEffect, useRef } from 'react';

const Hero = () => {
  const heroRef = useRef();

    useEffect(() => {
        const observer = new IntersectionObserver(
              entries => entries.forEach(e => e.isIntersecting && e.target.classList.add('visible')),
                    { threshold: 0.1 }
                        );
                            const elements = heroRef.current?.querySelectorAll('.fade-up');
                                elements?.forEach(el => observer.observe(el));
                                    return () => elements?.forEach(el => observer.unobserve(el));
                                      }, []);

                                        return (
                                            <section className="hero" id="home" ref={heroRef}>
                                                  <div className="hero-bg-gradient" />
                                                        <div className="hero-bg-gradient2" />
                                                              <div className="hero-grid" />

                                                                    <div className="hero-container">
                                                                            <div className="hero-content">
                                                                                      <div className="fade-up">
                                                                                                  <div className="hero-badge">
                                                                                                                <span className="hero-badge-dot" />
                                                                                                                              New Collection 2025
                                                                                                                                          </div>
                                                                                                                                                    </div>

                                                                                                                                                              <h1 className="hero-title fade-up stagger-1">
                                                                                                                                                                          <span className="hero-title-line">Discover</span>
                                                                                                                                                                                      <span className="hero-title-line hero-title-gradient">Premium</span>
                                                                                                                                                                                                  <span className="hero-title-line">Collection</span>
                                                                                                                                                                                                            </h1>

                                                                                                                                                                                                                      <p className="hero-desc fade-up stagger-2">
                                                                                                                                                                                                                                  Experience shopping reimagined with curated premium products, 
                                                                                                                                                                                                                                              exclusive deals, and a seamless shopping journey like never before.
                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                  <div className="hero-buttons fade-up stagger-3">
                                                                                                                                                                                                                                                                              <button className="hero-btn-primary" onClick={() => {
                                                                                                                                                                                                                                                                                            document.getElementById('products')?.scrollIntoView({ behavior: 'smooth' });
                                                                                                                                                                                                                                                                                                        }}>
                                                                                                                                                                                                                                                                                                                      🛍️ Shop Now
                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                              <button className="hero-btn-secondary">
                                                                                                                                                                                                                                                                                                                                                            ▶️ Watch Story
                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                            <div className="hero-stats fade-up stagger-4">
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="hero-stat">
                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="hero-stat-number">50K+</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="hero-stat-label">Happy Customers</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="hero-stat">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="hero-stat-number">10K+</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="hero-stat-label">Products</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="hero-stat">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="hero-stat-number">99%</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="hero-stat-label">Satisfaction</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="hero-visual fade-up stagger-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="hero-3d-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="hero-3d-card-bg" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="hero-3d-card-content">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="hero-3d-tag">🔥 Bestseller</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="hero-3d-image">👟</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="hero-3d-info">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="hero-3d-name">Air Max Velora Pro</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="hero-3d-price">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $299
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="hero-3d-old-price">$499</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="hero-float-card hero-float-card-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="hero-float-icon">⭐</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="hero-float-label">Rating</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="hero-float-value">4.9/5.0</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="hero-float-card hero-float-card-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="hero-float-icon">🚚</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="hero-float-label">Delivery</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="hero-float-value">Free Shipping</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default Hero;