import React, { useEffect, useRef, useState } from 'react';

const Hero = () => {
  const heroRef = useRef();
    const [mousePos, setMousePos] = useState({ x: 0, y: 0 });

      useEffect(() => {
          const observer = new IntersectionObserver(
                entries => entries.forEach(e => e.isIntersecting && e.target.classList.add('visible')),
                      { threshold: 0.1 }
                          );
                              heroRef.current?.querySelectorAll('.fade-up').forEach(el => observer.observe(el));

                                  const handleMouseMove = (e) => {
                                        const x = (e.clientX / window.innerWidth - 0.5) * 2;
                                              const y = (e.clientY / window.innerHeight - 0.5) * 2;
                                                    setMousePos({ x, y });
                                                        };
                                                            window.addEventListener('mousemove', handleMouseMove);

                                                                return () => {
                                                                      window.removeEventListener('mousemove', handleMouseMove);
                                                                          };
                                                                            }, []);

                                                                              return (
                                                                                  <section className="hero-3d" id="home" ref={heroRef}>
                                                                                        <div className="hero-3d-container">
                                                                                                <div className="hero-3d-content">
                                                                                                          <div className="fade-up">
                                                                                                                      <div className="hero-3d-badge">
                                                                                                                                    <span className="badge-pulse" />
                                                                                                                                                  New Collection 2025
                                                                                                                                                              </div>
                                                                                                                                                                        </div>

                                                                                                                                                                                  <h1 className="hero-3d-title fade-up stagger-1">
                                                                                                                                                                                              <span className="title-line">Discover</span>
                                                                                                                                                                                                          <span className="title-line title-gradient">Premium</span>
                                                                                                                                                                                                                      <span className="title-line title-outline">Collection</span>
                                                                                                                                                                                                                                </h1>

                                                                                                                                                                                                                                          <p className="hero-3d-desc fade-up stagger-2">
                                                                                                                                                                                                                                                      Experience shopping reimagined with curated premium products
                                                                                                                                                                                                                                                                  in a stunning 3D immersive environment.
                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                      <div className="hero-3d-buttons fade-up stagger-3">
                                                                                                                                                                                                                                                                                                  <button className="btn-3d-primary" onClick={() => document.getElementById('products')?.scrollIntoView({ behavior: 'smooth' })}>
                                                                                                                                                                                                                                                                                                                <span>🛍️ Shop Now</span>
                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                        <button className="btn-3d-secondary">
                                                                                                                                                                                                                                                                                                                                                      <span>▶️ Watch Story</span>
                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                      <div className="hero-3d-stats fade-up stagger-4">
                                                                                                                                                                                                                                                                                                                                                                                                  <div className="stat-3d">
                                                                                                                                                                                                                                                                                                                                                                                                                <div className="stat-3d-number">50K+</div>
                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="stat-3d-label">Customers</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="stat-3d">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="stat-3d-number">10K+</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="stat-3d-label">Products</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="stat-3d">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="stat-3d-number">99%</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="stat-3d-label">Satisfaction</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* 3D Floating Product Showcase with mouse parallax */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="hero-3d-visual fade-up stagger-3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    transform: `perspective(1500px) rotateY(${mousePos.x * 10}deg) rotateX(${-mousePos.y * 10}deg)`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="hero-3d-product-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="product-3d-glow" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="hero-3d-tag">🔥 Bestseller</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="hero-3d-product-image">👟</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="hero-3d-product-info">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="hero-3d-product-name">Air Max Velora Pro</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="hero-3d-product-price">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $299 <span>$499</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="card-reflection" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Floating satellite cards */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="hero-float-badge badge-1" style={{ transform: `translate(${mousePos.x * 20}px, ${mousePos.y * 20}px)` }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="float-icon">⭐</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="float-label">Rating</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="float-value">4.9/5.0</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="hero-float-badge badge-2" style={{ transform: `translate(${-mousePos.x * 15}px, ${-mousePos.y * 15}px)` }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="float-icon">🚚</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="float-label">Delivery</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="float-value">Free Shipping</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="hero-float-badge badge-3" style={{ transform: `translate(${mousePos.x * 10}px, ${-mousePos.y * 10}px)` }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="float-icon">💎</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="float-label">Quality</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="float-value">Premium</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* 3D orbit rings */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="orbit-ring ring-outer" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="orbit-ring ring-inner" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Scroll indicator */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="hero-scroll-indicator">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="scroll-mouse">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="scroll-wheel" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default Hero;