import React, { useState, useRef } from 'react';
import { useApp } from '../contexts/AppContext';

const LoginGate = () => {
  const { login } = useApp();
    const [email, setEmail] = useState('');
      const [password, setPassword] = useState('');
        const [isSignup, setIsSignup] = useState(false);
          const [error, setError] = useState('');
            const [loading, setLoading] = useState(false);
              const cardRef = useRef(null);
                const [tilt, setTilt] = useState({ x: 0, y: 0 });

                  const handleMouseMove = (e) => {
                      const card = cardRef.current;
                          if (!card) return;
                              const rect = card.getBoundingClientRect();
                                  const x = e.clientX - rect.left;
                                      const y = e.clientY - rect.top;
                                          const centerX = rect.width / 2;
                                              const centerY = rect.height / 2;
                                                  const rotateX = ((y - centerY) / centerY) * -8;
                                                      const rotateY = ((x - centerX) / centerX) * 8;
                                                          setTilt({ x: rotateX, y: rotateY });
                                                            };

                                                              const handleMouseLeave = () => setTilt({ x: 0, y: 0 });

                                                                const handleSubmit = (e) => {
                                                                    e.preventDefault();
                                                                        setError('');
                                                                            if (!email || !password) { setError('Please fill all fields'); return; }
                                                                                setLoading(true);
                                                                                    setTimeout(() => {
                                                                                          const result = login(email, password);
                                                                                                if (!result.success) setError(result.error || 'Invalid credentials');
                                                                                                      setLoading(false);
                                                                                                          }, 1200);
                                                                                                            };

                                                                                                              // Generate floating 3D orbs
                                                                                                                const orbs = Array.from({ length: 12 }, (_, i) => ({
                                                                                                                    id: i,
                                                                                                                        size: Math.random() * 100 + 40,
                                                                                                                            left: Math.random() * 100,
                                                                                                                                top: Math.random() * 100,
                                                                                                                                    delay: Math.random() * 5,
                                                                                                                                        duration: Math.random() * 10 + 10,
                                                                                                                                            color: ['#a855f7', '#6366f1', '#ec4899', '#06b6d4'][i % 4]
                                                                                                                                              }));

                                                                                                                                                return (
                                                                                                                                                    <div className="login-gate-3d">
                                                                                                                                                          {/* Floating 3D Orbs Background */}
                                                                                                                                                                <div className="login-orbs-container">
                                                                                                                                                                        {orbs.map(orb => (
                                                                                                                                                                                  <div
                                                                                                                                                                                              key={orb.id}
                                                                                                                                                                                                          className="login-floating-orb"
                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                    width: orb.size,
                                                                                                                                                                                                                                                  height: orb.size,
                                                                                                                                                                                                                                                                left: `${orb.left}%`,
                                                                                                                                                                                                                                                                              top: `${orb.top}%`,
                                                                                                                                                                                                                                                                                            background: `radial-gradient(circle, ${orb.color}40, transparent 70%)`,
                                                                                                                                                                                                                                                                                                          animationDelay: `${orb.delay}s`,
                                                                                                                                                                                                                                                                                                                        animationDuration: `${orb.duration}s`
                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                  {/* Animated Grid Floor (3D perspective) */}
                                                                                                                                                                                                                                                                                                                                                                        <div className="login-grid-floor" />

                                                                                                                                                                                                                                                                                                                                                                              {/* Main 3D Tilt Card */}
                                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                                            ref={cardRef}
                                                                                                                                                                                                                                                                                                                                                                                                    className="login-3d-card-wrapper"
                                                                                                                                                                                                                                                                                                                                                                                                            onMouseMove={handleMouseMove}
                                                                                                                                                                                                                                                                                                                                                                                                                    onMouseLeave={handleMouseLeave}
                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                      transform: `perspective(1200px) rotateX(${tilt.x}deg) rotateY(${tilt.y}deg)`
                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="login-3d-card-glow" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="login-3d-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="login-3d-shine" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="login-3d-logo">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="login-3d-logo-icon">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>🛒</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="logo-ring" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="logo-ring ring-2" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h1>VELORA<span>CART</span></h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>{isSignup ? 'Create your luxury account' : 'Enter the premium experience'}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {error && <div className="login-3d-error">⚠️ {error}</div>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <form onSubmit={handleSubmit} className="login-3d-form">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="login-3d-input-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder=" "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={e => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="login-3d-input"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label>Email Address</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="input-underline" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="login-3d-input-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder=" "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={e => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="login-3d-input"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label>Password</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="input-underline" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button type="submit" className="login-3d-btn" disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="btn-text">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {loading ? '✨ Authenticating...' : isSignup ? '🚀 Create Account' : '⚡ Enter VeloraCart'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="btn-shine" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="login-3d-footer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {isSignup ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <>Already a member? <span onClick={() => setIsSignup(false)}>Sign In</span></>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <>New here? <span onClick={() => setIsSignup(true)}>Create Account</span></>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="login-3d-hint">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                💡 Try any email + 6-char password to explore
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default LoginGate