import React, { useState, useEffect } from 'react';
import { useApp } from '../contexts/AppContext';

const Navbar = () => {
  const { user, logout, isAdmin, setIsAdminPanelOpen, cartCount, setIsCartOpen, wishlist, setIsWishlistOpen, theme, setTheme, searchQuery, setSearchQuery } = useApp();
    const [scrolled, setScrolled] = useState(false);
      const [mobileOpen, setMobileOpen] = useState(false);
        const [showUserMenu, setShowUserMenu] = useState(false);

          useEffect(() => {
              const handleScroll = () => setScrolled(window.scrollY > 50);
                  window.addEventListener('scroll', handleScroll);
                      return () => window.removeEventListener('scroll', handleScroll);
                        }, []);

                          const navLinks = ['Home', 'Products', 'Categories', 'Deals', 'About'];
                            const scrollTo = (id) => {
                                document.getElementById(id.toLowerCase())?.scrollIntoView({ behavior: 'smooth' });
                                    setMobileOpen(false);
                                      };

                                        return (
                                            <>
                                                  <nav className={`navbar-3d ${scrolled ? 'scrolled' : ''}`}>
                                                          <div className="nav-3d-container">
                                                                    <div className="nav-3d-logo" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>
                                                                                <div className="nav-3d-logo-box">🛒</div>
                                                                                            <span className="nav-3d-logo-text">VeloraCart</span>
                                                                                                      </div>

                                                                                                                <ul className="nav-3d-links">
                                                                                                                            {navLinks.map(link => (
                                                                                                                                          <li key={link} onClick={() => scrollTo(link)}>{link}</li>
                                                                                                                                                      ))}
                                                                                                                                                                </ul>

                                                                                                                                                                          <div className="nav-3d-actions">
                                                                                                                                                                                      <div className="nav-3d-search">
                                                                                                                                                                                                    <span>🔍</span>
                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                  type="text"
                                                                                                                                                                                                                                                  placeholder="Search products..."
                                                                                                                                                                                                                                                                  value={searchQuery}
                                                                                                                                                                                                                                                                                  onChange={e => setSearchQuery(e.target.value)}
                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                        <button className="nav-3d-icon-btn" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>
                                                                                                                                                                                                                                                                                                                                      {theme === 'dark' ? '☀️' : '🌙'}
                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                              <button className="nav-3d-icon-btn" onClick={() => setIsWishlistOpen(true)}>
                                                                                                                                                                                                                                                                                                                                                                            ❤️
                                                                                                                                                                                                                                                                                                                                                                                          {wishlist.length > 0 && <span className="nav-3d-badge">{wishlist.length}</span>}
                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                  <button className="nav-3d-icon-btn" onClick={() => setIsCartOpen(true)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                🛍️
                                                                                                                                                                                                                                                                                                                                                                                                                                              {cartCount > 0 && <span className="nav-3d-badge">{cartCount}</span>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="nav-3d-user" onClick={() => setShowUserMenu(!showUserMenu)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="nav-3d-avatar">{user?.avatar || 'U'}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span>{user?.name}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {showUserMenu && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="nav-3d-dropdown">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {isAdmin && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="dropdown-item admin-item" onClick={() => setIsAdminPanelOpen(true)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          👑 Admin Panel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="dropdown-item" onClick={logout}>🚪 Logout</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button className="nav-3d-mobile-toggle" onClick={() => setMobileOpen(true)}>☰</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </nav>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className={`mobile-menu-3d-overlay ${mobileOpen ? 'active' : ''}`} onClick={() => setMobileOpen(false)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className={`mobile-menu-3d ${mobileOpen ? 'active' : ''}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button className="mobile-close" onClick={() => setMobileOpen(false)}>✕</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {navLinks.map(link => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div key={link} className="mobile-link" onClick={() => scrollTo(link)}>{link}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {isAdmin && <div className="mobile-link admin" onClick={() => setIsAdminPanelOpen(true)}>👑 Admin Panel</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="mobile-link logout" onClick={logout}>🚪 Logout</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default Navbar