import React, { useState, useEffect } from 'react';
import { useCart } from '../context/CartContext';

const Navbar = ({ user, onLogout }) => {
  const [scrolled, setScrolled] = useState(false);
    const [mobileOpen, setMobileOpen] = useState(false);
      const { cartCount, setIsCartOpen } = useCart();

        useEffect(() => {
            const handleScroll = () => setScrolled(window.scrollY > 50);
                window.addEventListener('scroll', handleScroll);
                    return () => window.removeEventListener('scroll', handleScroll);
                      }, []);

                        const navLinks = ['Home', 'Products', 'Categories', 'Deals', 'About'];

                          const scrollTo = (id) => {
                              const el = document.getElementById(id.toLowerCase());
                                  if (el) el.scrollIntoView({ behavior: 'smooth' });
                                      setMobileOpen(false);
                                        };

                                          return (
                                              <>
                                                    <nav className={`navbar ${scrolled ? 'scrolled' : ''}`}>
                                                            <div className="nav-container">
                                                                      <div className="nav-logo" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>
                                                                                  <div className="nav-logo-box">🛒</div>
                                                                                              <span className="nav-logo-text">VeloraCart</span>
                                                                                                        </div>

                                                                                                                  <ul className="nav-links">
                                                                                                                              {navLinks.map(link => (
                                                                                                                                            <li key={link} className="nav-link" onClick={() => scrollTo(link)}>
                                                                                                                                                            {link}
                                                                                                                                                                          </li>
                                                                                                                                                                                      ))}
                                                                                                                                                                                                </ul>

                                                                                                                                                                                                          <div className="nav-actions">
                                                                                                                                                                                                                      <div className="nav-search">
                                                                                                                                                                                                                                    <span className="nav-search-icon">🔍</span>
                                                                                                                                                                                                                                                  <input type="text" placeholder="Search products..." />
                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                          <button className="nav-icon-btn" onClick={() => setIsCartOpen(true)}>
                                                                                                                                                                                                                                                                                        🛍️
                                                                                                                                                                                                                                                                                                      {cartCount > 0 && <span className="nav-cart-badge">{cartCount}</span>}
                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                              <div className="nav-user-btn" onClick={onLogout} title="Click to logout">
                                                                                                                                                                                                                                                                                                                                            <div className="nav-user-avatar">
                                                                                                                                                                                                                                                                                                                                                            {user?.name?.charAt(0)?.toUpperCase() || 'U'}
                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                        <span className="nav-user-name">{user?.name || 'User'}</span>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                <button className="nav-mobile-toggle" onClick={() => setMobileOpen(true)}>
                                                                                                                                                                                                                                                                                                                                                                                                                              ☰
                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </nav>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Mobile Menu */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className={`mobile-menu-overlay ${mobileOpen ? 'active' : ''}`} onClick={() => setMobileOpen(false)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className={`mobile-menu ${mobileOpen ? 'active' : ''}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mobile-menu-header">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="nav-logo">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="nav-logo-box">🛒</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="nav-logo-text">VeloraCart</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button className="nav-icon-btn" onClick={() => setMobileOpen(false)}>✕</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <ul className="mobile-menu-links">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {navLinks.map(link => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li key={link} className="mobile-menu-link" onClick={() => scrollTo(link)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {link}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <li className="mobile-menu-link" onClick={onLogout} style={{ color: '#ef4444', marginTop: 20 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  🚪 Logout
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default Navbar;