import React, { useState, useRef } from 'react';
import { useApp } from '../contexts/AppContext';

const ProductCard = ({ product, onQuickView }) => {
  const { addToCart, toggleWishlist, isInWishlist } = useApp();
    const cardRef = useRef(null);
      const [tilt, setTilt] = useState({ x: 0, y: 0 });
        const wishlisted = isInWishlist(product.id);

          const handleMouseMove = (e) => {
              const card = cardRef.current;
                  if (!card) return;
                      const rect = card.getBoundingClientRect();
                          const x = e.clientX - rect.left;
                              const y = e.clientY - rect.top;
                                  const rotateX = ((y - rect.height / 2) / rect.height) * -12;
                                      const rotateY = ((x - rect.width / 2) / rect.width) * 12;
                                          setTilt({ x: rotateX, y: rotateY });
                                            };

                                              const handleMouseLeave = () => setTilt({ x: 0, y: 0 });

                                                const handleAddToCart = (e) => {
                                                    e.stopPropagation();
                                                        addToCart(product);
                                                          };

                                                            const handleWishlist = (e) => {
                                                                e.stopPropagation();
                                                                    toggleWishlist(product);
                                                                      };

                                                                        return (
                                                                            <div
                                                                                  ref={cardRef}
                                                                                        className="product-card-3d"
                                                                                              onMouseMove={handleMouseMove}
                                                                                                    onMouseLeave={handleMouseLeave}
                                                                                                          onClick={() => onQuickView(product)}
                                                                                                                style={{
                                                                                                                        transform: `perspective(1000px) rotateX(${tilt.x}deg) rotateY(${tilt.y}deg) scale3d(1,1,1)`
                                                                                                                              }}
                                                                                                                                  >
                                                                                                                                        <div className="product-card-3d-shine" style={{ 
                                                                                                                                                background: `radial-gradient(circle at ${50 + tilt.y * 2}% ${50 - tilt.x * 2}%, rgba(255,255,255,0.15), transparent 60%)` 
                                                                                                                                                      }} />
                                                                                                                                                            
                                                                                                                                                                  <div className="product-3d-image-box">
                                                                                                                                                                          <div className="product-badges-3d">
                                                                                                                                                                                    {product.badge === 'new' && <span className="badge-3d badge-new">✨ New</span>}
                                                                                                                                                                                              {product.badge === 'sale' && <span className="badge-3d badge-sale">🔥 Sale</span>}
                                                                                                                                                                                                        {product.badge === 'hot' && <span className="badge-3d badge-hot">⚡ Hot</span>}
                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                        <button className={`wishlist-3d-btn ${wishlisted ? 'active' : ''}`} onClick={handleWishlist}>
                                                                                                                                                                                                                                  {wishlisted ? '❤️' : '🤍'}
                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                  <div className="product-3d-emoji">{product.emoji}</div>

                                                                                                                                                                                                                                                          <button className="quick-add-3d-btn" onClick={handleAddToCart}>
                                                                                                                                                                                                                                                                    🛒 Add to Cart
                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                        <div className="product-3d-info">
                                                                                                                                                                                                                                                                                                <div className="product-3d-category">{product.category}</div>
                                                                                                                                                                                                                                                                                                        <h3 className="product-3d-name">{product.name}</h3>
                                                                                                                                                                                                                                                                                                                <div className="product-3d-rating">
                                                                                                                                                                                                                                                                                                                          <span className="stars">{'★'.repeat(Math.floor(product.rating))}</span>
                                                                                                                                                                                                                                                                                                                                    <span className="review-count">({product.reviews})</span>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                    <div className="product-3d-price-row">
                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                          <span className="price-current">${product.price}</span>
                                                                                                                                                                                                                                                                                                                                                                                      <span className="price-old">${product.oldPrice}</span>
                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                          <div className="product-3d-colors">
                                                                                                                                                                                                                                                                                                                                                                                                                      {product.colors?.map((c, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                    <span key={i} className="color-dot" style={{ background: c }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {product.stock < 10 && product.stock > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="stock-warning">⚠️ Only {product.stock} left!</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {product.stock === 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="stock-out">❌ Out of Stock</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default ProductCard;