import React, { useState } from 'react';
import { useApp } from '../contexts/AppContext';

const ProductModal = ({ product, onClose }) => {
  const { addToCart, toggleWishlist, isInWishlist } = useApp();
    const [selectedSize, setSelectedSize] = useState('M');
      const [quantity, setQuantity] = useState(1);
        const [rotateY, setRotateY] = useState(0);
          const sizes = ['XS', 'S', 'M', 'L', 'XL'];
            const wishlisted = isInWishlist(product.id);

              const handleAdd = () => {
                  addToCart(product, quantity);
                      onClose();
                        };

                          const rotateProduct = (dir) => {
                              setRotateY(prev => prev + (dir * 90));
                                };

                                  return (
                                      <div className="modal-3d-overlay active" onClick={onClose}>
                                            <div className="modal-3d-content" onClick={e => e.stopPropagation()}>
                                                    <button className="modal-3d-close" onClick={onClose}>✕</button>
                                                            
                                                                    <div className="modal-3d-grid">
                                                                              <div className="modal-3d-image-section">
                                                                                          <button className="rotate-btn rotate-left" onClick={() => rotateProduct(-1)}>↺</button>
                                                                                                      <div 
                                                                                                                    className="modal-3d-product-display"
                                                                                                                                  style={{ transform: `perspective(800px) rotateY(${rotateY}deg)` }}
                                                                                                                                              >
                                                                                                                                                            <span className="modal-3d-emoji">{product.emoji}</span>
                                                                                                                                                                        </div>
                                                                                                                                                                                    <button className="rotate-btn rotate-right" onClick={() => rotateProduct(1)}>↻</button>
                                                                                                                                                                                                <div className="modal-3d-floor-shadow" />
                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                    <div className="modal-3d-details">
                                                                                                                                                                                                                                <div className="modal-3d-category">{product.category}</div>
                                                                                                                                                                                                                                            <h2 className="modal-3d-name">{product.name}</h2>

                                                                                                                                                                                                                                                        <div className="modal-3d-rating">
                                                                                                                                                                                                                                                                      <span className="stars">{'⭐'.repeat(Math.floor(product.rating))}</span>
                                                                                                                                                                                                                                                                                    <span>{product.rating} ({product.reviews} reviews)</span>
                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                            <div className="modal-3d-price">
                                                                                                                                                                                                                                                                                                                          ${product.price}
                                                                                                                                                                                                                                                                                                                                        <span className="modal-old-price">${product.oldPrice}</span>
                                                                                                                                                                                                                                                                                                                                                      <span className="modal-discount">
                                                                                                                                                                                                                                                                                                                                                                      {Math.round((1 - product.price / product.oldPrice) * 100)}% OFF
                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                            <p className="modal-3d-desc">{product.desc}</p>

                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="modal-3d-option-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="option-label">Select Size</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="size-selector">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {sizes.map(size => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          key={size}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className={`size-btn ${selectedSize === size ? 'active' : ''}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => setSelectedSize(size)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {size}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="modal-3d-option-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="option-label">Colors</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="color-selector">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {product.colors?.map((c, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span key={i} className="color-swatch" style={{ background: c }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="modal-3d-option-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="option-label">Quantity</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="qty-selector">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={() => setQuantity(Math.max(1, quantity - 1))}>−</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>{quantity}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={() => setQuantity(quantity + 1)}>+</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="modal-3d-stock">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {product.stock > 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="in-stock">✅ In Stock ({product.stock} available)</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="out-stock">❌ Out of Stock</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="modal-3d-actions">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="modal-add-cart-btn" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={handleAdd}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      disabled={product.stock === 0}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    🛒 Add to Cart — ${(product.price * quantity).toFixed(2)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className={`modal-wishlist-btn ${wishlisted ? 'active' : ''}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => toggleWishlist(product)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {wishlisted ? '❤️' : '🤍'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default ProductModal;