import React, { useState } from 'react';
import { useCart } from '../context/CartContext';

const ProductModal = ({ product, onClose }) => {
  const [selectedSize, setSelectedSize] = useState('M');
    const { addToCart } = useCart();
      const sizes = ['XS', 'S', 'M', 'L', 'XL'];

        if (!product) return null;

          const handleAdd = () => {
              addToCart(product);
                  onClose();
                    };

                      return (
                          <div className={`modal-overlay ${product ? 'active' : ''}`} onClick={onClose}>
                                <div className="modal-content" onClick={e => e.stopPropagation()}>
                                        <button className="modal-close" onClick={onClose}>✕</button>
                                                <div className="modal-grid">
                                                          <div className="modal-image">
                                                                      <span style={{ fontSize: '150px', filter: 'drop-shadow(0 20px 40px rgba(0,0,0,0.3))' }}>
                                                                                    {product.emoji}
                                                                                                </span>
                                                                                                          </div>

                                                                                                                    <div className="modal-details">
                                                                                                                                <div className="modal-category">{product.category}</div>
                                                                                                                                            <h2 className="modal-name">{product.name}</h2>

                                                                                                                                                        <div className="modal-rating">
                                                                                                                                                                      <span className="product-stars">{'⭐'.repeat(Math.floor(product.rating))}</span>
                                                                                                                                                                                    <span className="product-rating-count">{product.rating} ({product.reviews} reviews)</span>
                                                                                                                                                                                                </div>

                                                                                                                                                                                                            <div className="modal-price">
                                                                                                                                                                                                                          ${product.price}
                                                                                                                                                                                                                                        <span className="hero-3d-old-price">${product.oldPrice}</span>
                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                <p className="modal-desc">{product.desc}</p>

                                                                                                                                                                                                                                                                            <div className="modal-options">
                                                                                                                                                                                                                                                                                          <div className="modal-option-label">Select Size</div>
                                                                                                                                                                                                                                                                                                        <div className="modal-sizes">
                                                                                                                                                                                                                                                                                                                        {sizes.map(size => (
                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                              key={size}
                                                                                                                                                                                                                                                                                                                                                                                  className={`modal-size ${selectedSize === size ? 'active' : ''}`}
                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => setSelectedSize(size)}
                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                            {size}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="modal-options" style={{ marginBottom: 0 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="modal-option-label">Colors</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="product-colors">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {product.colors?.map((color, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span key={i} className="product-color" style={{ background: color, width: 24, height: 24 }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button className="modal-add-btn" onClick={handleAdd}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      🛒 Add to Cart — ${product.price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default ProductModal;