import React, { useEffect, useRef } from 'react';

const ThreeDBackground = () => {
  const canvasRef = useRef(null);
    const mouseRef = useRef({ x: null, y: null });

      useEffect(() => {
          const canvas = canvasRef.current;
              const ctx = canvas.getContext('2d');
                  let animationId;
                      let width = (canvas.width = window.innerWidth);
                          let height = (canvas.height = window.innerHeight);

                              const handleResize = () => {
                                    width = canvas.width = window.innerWidth;
                                          height = canvas.height = window.innerHeight;
                                              };
                                                  const handleMouseMove = (e) => {
                                                        mouseRef.current = { x: e.clientX, y: e.clientY };
                                                            };
                                                                const handleTouchMove = (e) => {
                                                                      if (e.touches[0]) mouseRef.current = { x: e.touches[0].clientX, y: e.touches[0].clientY };
                                                                          };
                                                                              const handleMouseLeave = () => { mouseRef.current = { x: null, y: null }; };

                                                                                  window.addEventListener('resize', handleResize);
                                                                                      window.addEventListener('mousemove', handleMouseMove);
                                                                                          window.addEventListener('touchmove', handleTouchMove);
                                                                                              window.addEventListener('mouseleave', handleMouseLeave);

                                                                                                  const particleCount = window.innerWidth < 768 ? 60 : 130;
                                                                                                      const particles = [];
                                                                                                          const colors = ['#a855f7', '#6366f1', '#ec4899', '#06b6d4', '#f59e0b'];

                                                                                                              class Particle {
                                                                                                                    constructor() {
                                                                                                                            this.reset();
                                                                                                                                    this.z = Math.random() * 2 + 0.5; // depth for parallax
                                                                                                                                          }
                                                                                                                                                reset() {
                                                                                                                                                        this.x = Math.random() * width;
                                                                                                                                                                this.y = Math.random() * height;
                                                                                                                                                                        this.baseRadius = Math.random() * 2.2 + 0.8;
                                                                                                                                                                                this.radius = this.baseRadius;
                                                                                                                                                                                        this.color = colors[Math.floor(Math.random() * colors.length)];
                                                                                                                                                                                                this.vx = (Math.random() - 0.5) * 0.4;
                                                                                                                                                                                                        this.vy = (Math.random() - 0.5) * 0.4;
                                                                                                                                                                                                                this.alpha = Math.random() * 0.6 + 0.3;
                                                                                                                                                                                                                        this.pulseSpeed = Math.random() * 0.02 + 0.01;
                                                                                                                                                                                                                                this.pulseOffset = Math.random() * Math.PI * 2;
                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                            update(time) {
                                                                                                                                                                                                                                                    // Depth parallax movement
                                                                                                                                                                                                                                                            this.x += this.vx * this.z;
                                                                                                                                                                                                                                                                    this.y += this.vy * this.z;

                                                                                                                                                                                                                                                                            // Pulse effect (3D breathing)
                                                                                                                                                                                                                                                                                    this.radius = this.baseRadius + Math.sin(time * this.pulseSpeed + this.pulseOffset) * 0.8;

                                                                                                                                                                                                                                                                                            // Mouse attraction (3D tilt feel)
                                                                                                                                                                                                                                                                                                    const mx = mouseRef.current.x;
                                                                                                                                                                                                                                                                                                            const my = mouseRef.current.y;
                                                                                                                                                                                                                                                                                                                    if (mx !== null) {
                                                                                                                                                                                                                                                                                                                              const dx = mx - this.x;
                                                                                                                                                                                                                                                                                                                                        const dy = my - this.y;
                                                                                                                                                                                                                                                                                                                                                  const dist = Math.sqrt(dx * dx + dy * dy);
                                                                                                                                                                                                                                                                                                                                                            if (dist < 180) {
                                                                                                                                                                                                                                                                                                                                                                        const force = (180 - dist) / 180;
                                                                                                                                                                                                                                                                                                                                                                                    this.x -= (dx / dist) * force * 2.2;
                                                                                                                                                                                                                                                                                                                                                                                                this.y -= (dy / dist) * force * 2.2;
                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                          if (this.x < -20) this.x = width + 20;
                                                                                                                                                                                                                                                                                                                                                                                                                                  if (this.x > width + 20) this.x = -20;
                                                                                                                                                                                                                                                                                                                                                                                                                                          if (this.y < -20) this.y = height + 20;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (this.y > height + 20) this.y = -20;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                              draw(ctx) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ctx.arc(this.x, this.y, this.radius * this.z, 0, Math.PI * 2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.fillStyle = this.color;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ctx.globalAlpha = this.alpha;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.shadowBlur = 15 * this.z;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ctx.shadowColor = this.color;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.fill();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ctx.globalAlpha = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.shadowBlur = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (let i = 0; i < particleCount; i++) particles.push(new Particle());

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let time = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const render = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  time += 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ctx.clearRect(0, 0, width, height);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Radial 3D glow gradient background
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const gradient = ctx.createRadialGradient(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            width / 2, height / 2, 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width / 2, height / 2, width / 1.2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gradient.addColorStop(0, 'rgba(168, 85, 247, 0.03)');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      gradient.addColorStop(1, 'rgba(10, 10, 15, 0)');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ctx.fillStyle = gradient;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ctx.fillRect(0, 0, width, height);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Connect nearby particles (constellation/web effect)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              for (let i = 0; i < particles.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      for (let j = i + 1; j < particles.length; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const dx = particles[i].x - particles[j].x;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const dy = particles[i].y - particles[j].y;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const dist = Math.sqrt(dx * dx + dy * dy);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (dist < 110) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.strokeStyle = `rgba(168, 85, 247, ${0.12 * (1 - dist / 110)})`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ctx.lineWidth = 0.6;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ctx.moveTo(particles[i].x, particles[i].y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ctx.lineTo(particles[j].x, particles[j].y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.stroke();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Mouse glow ring (3D cursor effect)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (mouseRef.current.x !== null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const mx = mouseRef.current.x;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const my = mouseRef.current.y;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const ringGrad = ctx.createRadialGradient(mx, my, 0, mx, my, 150);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ringGrad.addColorStop(0, 'rgba(168, 85, 247, 0.15)');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ringGrad.addColorStop(1, 'rgba(168, 85, 247, 0)');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ctx.fillStyle = ringGrad;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ctx.arc(mx, my, 150, 0, Math.PI * 2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ctx.fill();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              particles.sort((a, b) => a.z - b.z); // draw back-to-front for depth
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    particles.forEach(p => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            p.update(time);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    p.draw(ctx);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                animationId = requestAnimationFrame(render);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        render();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cancelAnimationFrame(animationId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        window.removeEventListener('resize', handleResize);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              window.removeEventListener('mousemove', handleMouseMove);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    window.removeEventListener('touchmove', handleTouchMove);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          window.removeEventListener('mouseleave', handleMouseLeave);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return <canvas ref={canvasRef} className="threed-bg-canvas" />;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default ThreeDBackground