import React from 'react';
import { useApp } from '../contexts/AppContext';

const Wishlist = () => {
  const { wishlist, toggleWishlist, addToCart, isWishlistOpen, setIsWishlistOpen } = useApp();

    return (
        <>
              <div className={`cart-3d-overlay ${isWishlistOpen ? 'active' : ''}`} onClick={() => setIsWishlistOpen(false)} />
                    <div className={`wishlist-3d-sidebar ${isWishlistOpen ? 'active' : ''}`}>
                            <div className="cart-3d-header">
                                      <h3>❤️ Wishlist <span className="cart-3d-count">{wishlist.length}</span></h3>
                                                <button className="cart-3d-close" onClick={() => setIsWishlistOpen(false)}>✕</button>
                                                        </div>

                                                                <div className="cart-3d-items">
                                                                          {wishlist.length === 0 ? (
                                                                                      <div className="cart-3d-empty">
                                                                                                    <div className="empty-icon">💔</div>
                                                                                                                  <p>Your wishlist is empty</p>
                                                                                                                                <span>Save items you love for later!</span>
                                                                                                                                            </div>
                                                                                                                                                      ) : (
                                                                                                                                                                  wishlist.map(item => (
                                                                                                                                                                                <div key={item.id} className="wishlist-3d-item">
                                                                                                                                                                                                <div className="cart-3d-item-img">{item.emoji}</div>
                                                                                                                                                                                                                <div className="cart-3d-item-info">
                                                                                                                                                                                                                                  <div className="cart-3d-item-name">{item.name}</div>
                                                                                                                                                                                                                                                    <div className="cart-3d-item-price">${item.price}</div>
                                                                                                                                                                                                                                                                      <div className="wishlist-item-actions">
                                                                                                                                                                                                                                                                                          <button className="move-to-cart-btn" onClick={() => { addToCart(item); toggleWishlist(item); }}>
                                                                                                                                                                                                                                                                                                                🛒 Move to Cart
                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                        <button className="remove-btn" onClick={() => toggleWishlist(item)}>🗑️</button>
                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                    ))
                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default Wishlist;